@extends('layouts.app')

@section('content')
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow-lg border-0">
                <div class="card-header bg-primary text-white border-0 p-4">
                    <h4 class="mb-0">
                        <i class="bi bi-shield-plus me-2"></i>Enable Two-Factor Authentication
                    </h4>
                </div>
                
                <div class="card-body p-4">
                    @if(session('error'))
                        <div class="alert alert-danger">
                            <i class="bi bi-exclamation-triangle me-2"></i>{{ session('error') }}
                        </div>
                    @endif

                    <div class="text-center mb-4">
                        <p class="text-muted mb-4">Scan this QR code with your authenticator app</p>
                        
                        <div class="bg-light p-4 rounded d-inline-block mb-3">
                            <img src="{{ $qrCodeImage }}" alt="QR Code" class="img-fluid" style="max-width: 250px;">
                        </div>

                        <p class="small text-muted">
                            <i class="bi bi-info-circle me-1"></i>
                            Or manually enter this code:
                        </p>
                        <div class="bg-light p-3 rounded mb-3">
                            <code class="fs-5">{{ $secret }}</code>
                            <button type="button" class="btn btn-sm btn-outline-secondary ms-2" onclick="copySecret()">
                                <i class="bi bi-clipboard"></i> Copy
                            </button>
                        </div>
                    </div>

                    <hr class="my-4">

                    <h6 class="mb-3">Verify Setup</h6>
                    <p class="text-muted small">Enter the 6-digit code from your authenticator app to complete setup</p>

                    <form action="{{ route('2fa.confirm') }}" method="POST">
                        @csrf
                        
                        <div class="mb-4">
                            <label for="code" class="form-label">Verification Code</label>
                            <input type="text" 
                                   id="code"
                                   name="code" 
                                   class="form-control form-control-lg text-center @error('code') is-invalid @enderror" 
                                   placeholder="000000"
                                   maxlength="6"
                                   pattern="[0-9]{6}"
                                   autofocus
                                   required>
                            @error('code')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                            <small class="form-text text-muted">
                                Enter the 6-digit code generated by your authenticator app
                            </small>
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary btn-lg">
                                <i class="bi bi-check-circle me-2"></i>Verify & Enable 2FA
                            </button>
                            <a href="{{ route('2fa.index') }}" class="btn btn-outline-secondary">
                                <i class="bi bi-x-circle me-2"></i>Cancel
                            </a>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Instructions Card -->
            <div class="card shadow-sm border-0 mt-4">
                <div class="card-body p-4">
                    <h6 class="mb-3">
                        <i class="bi bi-question-circle me-2"></i>Need Help?
                    </h6>
                    <ol class="small text-muted mb-0 ps-3">
                        <li class="mb-2">Open your authenticator app (Google Authenticator, Authy, etc.)</li>
                        <li class="mb-2">Tap the "+" button to add a new account</li>
                        <li class="mb-2">Scan the QR code above or manually enter the secret key</li>
                        <li class="mb-2">Enter the 6-digit code shown in the app</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function copySecret() {
    const secret = '{{ $secret }}';
    navigator.clipboard.writeText(secret).then(() => {
        const btn = event.target.closest('button');
        const originalHTML = btn.innerHTML;
        btn.innerHTML = '<i class="bi bi-check"></i> Copied!';
        btn.classList.add('btn-success');
        btn.classList.remove('btn-outline-secondary');
        
        setTimeout(() => {
            btn.innerHTML = originalHTML;
            btn.classList.remove('btn-success');
            btn.classList.add('btn-outline-secondary');
        }, 2000);
    });
}

// Auto-format the code input
document.getElementById('code').addEventListener('input', function(e) {
    this.value = this.value.replace(/\D/g, '').slice(0, 6);
});

// Auto-submit when 6 digits entered
document.getElementById('code').addEventListener('input', function(e) {
    if (this.value.length === 6 && /^\d{6}$/.test(this.value)) {
        this.form.submit();
    }
});
</script>
@endsection
